"""sqlite_support

Revision ID: 43bb391d9027
Revises: f96a0f3a9ace
Create Date: 2021-11-22 21:41:53.260903

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '43bb391d9027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('ranking', sa.Integer(), nullable=False),
                    sa.Column('total_participants', sa.Integer(), nullable=True),
                    sa.Column('wpm', sa.Integer(), nullable=True),
                    sa.Column('epm', sa.Integer(), nullable=True),
                    sa.Column('accuracy', sa.Integer(), nullable=True),
                    sa.Column('time', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=32), nullable=False),
                    sa.Column('password_hash', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('race_members',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('race_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('statistics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('best_wpm', sa.Integer(), nullable=True),
                    sa.Column('best_accuracy', sa.Integer(), nullable=True),
                    sa.Column('total_races', sa.Integer(), nullable=True),
                    sa.Column('total_wins', sa.Integer(), nullable=True),
                    sa.Column('average_wpm', sa.Float(), nullable=True),
                    sa.Column('average_epm', sa.Float(), nullable=True),
                    sa.Column('average_accuracy', sa.Float(), nullable=True),
                    sa.Column('average_time', sa.Float(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('words',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('words', sa.Text(), nullable=False),
                    sa.Column('words_title', sa.String(length=50), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('statistics')
    op.drop_table('race_members')
    op.drop_table('users')
    op.drop_table('races')
    # ### end Alembic commands ###
